### ISSUE TITLE
Embershard Mine Revisited 1.1.1

### ISSUE THREAD

**Issue by Tetrol88** [ErikJohnsson/DungeonsRevisited#28]
Love your mods. Just entered Embershard with 1.1.1 and encountered an issue with the locked area with Master Chest etc. From the window (First Shot) can see a blank wall behind a fallen beam. Going around to the gate can see in, but the fallen beam is present (Second shot). If you walk into the beam (trying to see If I could get under it) the character becomes stuck and turning on no clipping is required to move. (if you go into the room, the view is per the window shot - a blank wall)
![ScreenShot7](https://user-images.githubusercontent.com/66471252/98785695-eac7a900-244c-11eb-8179-7d34b62d403e.png)
![ScreenShot8](https://user-images.githubusercontent.com/66471252/98785713-f1eeb700-244c-11eb-9988-87f7f40f9411.png)

**Comment by geraintwd** [comment]
I can confirm I have experienced the same issue. Not sure if this is because I approached this section from the (vanilla) final area with the forge, while the bridge was still raised.

![ScreenShot82](https://user-images.githubusercontent.com/16326425/99444885-b5233400-2914-11eb-95bf-ba7c5f5deec9.jpg)

**Comment by ErikJohnsson** [comment]
I will take a loot at this! Thanks for reporting.
