### ISSUE TITLE
Bleak Falls Barrow - Unpopulated other than Vanilla

### ISSUE THREAD

**Issue by Tetrol88** [ErikJohnsson/DungeonsRevisited#33]
Hi 

Have run through BFBR on two playthroughs now and found that while the vanilla enemies are present, none of the BFBR mobs are present - except one, and the same one each time. First room off the LEFT side of the passage accessed by either of two EXPERT lvl locked doors - should have 2 draugr patrolling and one rises from it's casket - only the one that rises is present. Not a single other BFBR enemy present in any of the BFBR cells.
Other mods that affect Block 8 sub block 5 (iirc) include cheesemod and an amulet mod - both the cheeses and the amulets were there. On the other hand, yesterday I installed Mihails ghouls, and I saw there were meant to be 4 ghouls present in there and they were not. That was not on the mod list the previous time when no mobs were present so it is similarly affected rather than to blame.
Any ideas what would be stopping the spawns. Could it be level related? - these play throughs I have been turning my xp all but off and I have got through only at lvl 5.

**Comment by geraintwd** [comment]
Sounds like something is affecting your levelled NPCs lists - have you tried rebuilding your Bashed Patch to merge levelled lists?

**Comment by Tetrol88** [comment]
Thanks - Just went through with another new character - and having changed mods around - including my bashed patch - and the spawns were back to normal - so  this may have been it. I always re-do my bashed patch when I have significant mod changes - but it does then take a fair bit to patch the patch as I find it often overwrites some mods. (Just found it doesn't like a lot of the realistic conquering series)

**Comment by geraintwd** [comment]
Here's a tip for making your Bashed Patch, at least as far as Skyrim SE is concerned - uncheck all of the boxes, except for levelled lists. That's generally the only thing you should use your BP for. Apart from that, I used it to make a separate patch that merged the cell edits from Sounds of Skyrim, Enhanced Lighting for ENB and Water for ENB, so that they didn't overwrite each other.
For any other conflict resolution, I would recommend doing this manually, by copying conflicting records as override into a new patch in xEdit. Hope this helps.

**Comment by Tetrol88** [comment]
Thx for that - changing a few other things atm (putting together the Fort Takeovers/Skyrim Realistic Conquering/Lawbringer mods, and doing some Draugr upgrades) so will be going through the process again.
